---

name: Integration

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - '**/*.rst'
    branches:
      - master
      - '[0-9].[0-9]'
  pull_request:
    branches:
      - master
      - '[0-9].[0-9]'
  schedule:
    - cron: '0 1 * * *' # nightly build

jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        redis-version: ['5.0', '6.0', '6.2', '7.0', 'unstable']
    steps:
      - uses: actions/checkout@v2
      - name: Set up publishing to maven central
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: System setup
        run: |
          sudo apt update
          sudo apt install -y stunnel make
          make system-setup REDIS_VERSION=${{matrix.redis-version}}
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            /var/cache/apt
          key: jedis-${{hashFiles('**/pom.xml')}}
      - name: Maven offline
        run: |
          mvn -q dependency:go-offline
      - name: Build docs
        run: |
          mvn -q javadoc:jar
      - name: Run tests
        run: |
          TEST="" make test REDIS_VERSION=${{matrix.redis-version}}
        env:
          JVM_OPTS: -Xmx3200m
          TERM: dumb
      - name: Make - start
        run: make start
      - name: Test commands - default protocol
        run: mvn -q -Dtest="redis.clients.jedis.commands.**" test
      - name: Test module commands - default protocol
        if: ${{matrix.redis-version == 'unstable'}}
        run: mvn -q -DmodulesDocker="localhost:52567" -Dtest="redis.clients.jedis.modules.**" test
      - name: Make - stop
        run: make stop
      - name: Codecov
        run: |
          bash <(curl -s https://codecov.io/bash)

  resp-3:
    name: RESP3 Tests
    runs-on: ubuntu-latest
    services:
      redis-stack:
        image: redis/redis-stack-server:edge
        ports:
          - 52567:6379
    steps:
      - uses: actions/checkout@v2
      - name: Set up publishing to maven central
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: System setup
        run: |
          sudo apt update -yqq
          sudo apt install -yqq stunnel make
          make system-setup
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            /var/cache/apt
          key: jedis-${{hashFiles('**/pom.xml')}}
      - name: Maven offline
        run: |
          mvn -q dependency:go-offline
      - name: Build docs
        run: |
          mvn -q javadoc:jar
      - name: Make - start
        run: make start
      - name: Test commands - RESP3 protocol
        run: mvn -q -DjedisProtocol=3 -Dtest="redis.clients.jedis.commands.**" test
      - name: Test module commands - RESP3 protocol
        run: mvn -q -DjedisProtocol=3 -DmodulesDocker="localhost:52567" -Dtest="redis.clients.jedis.modules.**" test
      - name: Make - stop
        run: make stop